name: Test
on: [push, pull_request]
jobs:
  test:
    name: Run Validation Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v1

      - name: Validation Tests
        run: |
          pip install pytest pandas
          pytest tests/tests